apiVersion: v1
kind: Service
metadata:
  name: musa
  namespace: imogen
spec:
  type: ClusterIP
  selector:
    app: musa
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000