name: Generic.BuildAndPublishDockerImage
on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      image_name:
        required: true
        type: string
      manifests:
        required: true
        type: string
      deployment_name:
        required: true
        type: string
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
env:
  PROJECT_ID: ${{ vars.GKE_PROJECT }}
  CLUSTER_NAME: ${{ vars.GKE_CLUSTER }}
  CLUSTER_LOCATION: ${{ vars.GKE_ZONE }}
  ARTIFACT_REPOSITORY_NAME: ${{ vars.GKE_ARTIFACT_REPOSITORY_NAME }}
  ARTIFACT_REPOSITORY_LOCATION: ${{ vars.GKE_ARTIFACT_REPOSITORY_LOCATION }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.GKE_SA_KEY }}
  IMAGE_TAG: "${{ vars.GKE_ARTIFACT_REPOSITORY_LOCATION }}/${{ vars.GKE_PROJECT }}/${{ vars.GKE_ARTIFACT_REPOSITORY_NAME }}/${{ inputs.IMAGE_NAME }}:${{ github.run_id }}${{ github.sha }}"
jobs:
  build-and-publish:
    name: Setup, Build, and Publish to Artifact Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.SERVICE_ACCOUNT_KEY }}'

      - name: Set up the Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker authentication
        run: gcloud --quiet auth configure-docker ${{ env.ARTIFACT_REPOSITORY_LOCATION }}

      - name: Build
        run: |-
          docker build \
            -f ${{ inputs.dockerfile }} \
            --tag "${{ env.IMAGE_TAG }}" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            ${{ inputs.context }}

      - name: Publish
        run: docker push ${{ env.IMAGE_TAG }}
  
  deploy:
    name: Deploy to GKE
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.SERVICE_ACCOUNT_KEY }}'

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_LOCATION }}

      - name: Update ImageName
        uses: richardrigutins/replace-in-files@v2
        with:
          search-text: ImageName
          files: ${{ inputs.manifests }}/*.yaml
          replacement-text: ${{ env.IMAGE_TAG }}
          encoding: utf8
          max-parallelism: 10

      - name: Deploy
        working-directory: ${{ inputs.manifests }}
        run: |-
          kubectl apply -f .;
          kubectl rollout status deployment ${{ inputs.deployment_name }} --namespace ${{ inputs.namespace }} --timeout 3m;
